// Shared menu icon map (Sidebar + ModuleLauncher)

import {
  LayoutDashboard,
  Home,
  Users,
  Shield,
  Menu,
  Building2,
  Network,
  FileText,
  CheckSquare,
  Ticket,
  ShoppingCart,
  Package,
  UserCheck,
  FolderOpen,
  Settings,
  Tag,
  Layers,
  Warehouse,
  ClipboardList,
  Calendar,
  DollarSign,
  User,
  Mail,
  Bot,
  Newspaper,
  BookOpen,
  type LucideIcon,
} from 'lucide-react'
import { FacebookIcon } from '@/components/shared/FacebookIcon'
import type { MenuTreeNode } from '../types/menu.types'

/** Facebook brand icon — cast for LucideIcon map compatibility. */
const FbIcon = FacebookIcon as unknown as LucideIcon

export const MENU_ICON_MAP: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  home: Home,
  users: Users,
  user: User,
  usercheck: UserCheck,
  shield: Shield,
  menu: Menu,
  building: Building2,
  network: Network,
  filetext: FileText,
  task: CheckSquare,
  listchecks: CheckSquare,
  ticket: Ticket,
  cart: ShoppingCart,
  shoppingcart: ShoppingCart,
  package: Package,
  customer: UserCheck,
  folder: FolderOpen,
  settings: Settings,
  tag: Tag,
  layers: Layers,
  warehouse: Warehouse,
  clipboard: ClipboardList,
  clipboardlist: ClipboardList,
  calendar: Calendar,
  dollar: DollarSign,
  dollarsign: DollarSign,
  bot: Bot,
  MENU_HRM: Users,
  MENU_CRM: UserCheck,
  MENU_PRODUCT: Package,
  MENU_WAREHOUSE: Warehouse,
  MENU_ACCOUNTING: DollarSign,
  MENU_APPROVAL: ClipboardList,
  MENU_TASK: CheckSquare,
  MENU_GROWTH: Bot,
  MENU_QTHT: Settings,
  MENU_TOOL: CheckSquare,
  MENU_SALE: ShoppingCart,
  QTHT: Settings,
  QLNS: ClipboardList,
  HRM: Users,
  CRM: UserCheck,
  TOOL: CheckSquare,
  SALE: ShoppingCart,
  PRODUCT: Package,
  GROWTH: Bot,
  APPROVAL: ClipboardList,
  ACCOUNTING: DollarSign,
  DMDC: Layers,
  CUSTOMER: UserCheck,
  EMAIL: Mail,
  QLHT_EMAIL: Mail,
  EMAIL_GROUP: Users,
  TASK: CheckSquare,
  FB: FbIcon,
  FACEBOOK: FbIcon,
  fb: FbIcon,
  automation: Bot,
  layouttemplate: LayoutDashboard,
  newspaper: Newspaper,
  globe: LayoutDashboard,
  book: BookOpen,
  bookopen: BookOpen,
  DEFAULT: FolderOpen,
}

export function getMenuIcon(node: Pick<MenuTreeNode, 'icon' | 'code'>): LucideIcon {
  const iconKey = node.icon?.toLowerCase() || node.code.split('_')[0]
  return MENU_ICON_MAP[iconKey] || MENU_ICON_MAP[node.code] || MENU_ICON_MAP.DEFAULT
}
